import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { SideNav } from "@/app/_components/SideNav";
import { TRPCReactProvider } from "@/trpc/react";
import { getServerSession } from "next-auth";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Social Z",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  const user = session?.user;

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <div className="container mx-auto flex items-start sm:pr-4">
            <SideNav user={user} />
            <div className="min-h-screen flex-grow border-x">{children}</div>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
